version: '3.4'

services:
  catalogdb:
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: CatalogDb

  basketdb:
    ports:
      - "6379:6379"

  discountdb:
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  orderingdb:
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"Password@1\" -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog.api:
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DatabaseSettings__ConnectionString=mongodb://root:password@catalogdb:27017/CatalogDb?authSource=admin
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__ProductsCollection=Products
      - DatabaseSettings__BrandsCollection=Brands
      - DatabaseSettings__TypesCollection=Types
    volumes:
      - ./Services/Catalog/Catalog.Infrastructure/Data/SeedData:/app/Data/SeedData

  basket.api:
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - GrpcSettings__DiscountUrl=http://discount.api:8080

  discount.api:
    ports:
      - "8002:8080"
    depends_on:
      discountdb:
        condition: service_healthy

  ordering.api:
    ports:
      - "8003:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__OrderingConnectionString=Server=orderingdb;Database=OrderingDb;User Id=sa;Password=Password@1;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      orderingdb:
        condition: service_healthy


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - discountdb
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eCommerce.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"

volumes:
  pgadmin_data:
  portainer_data:

