version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    volumes:
      - mongo_data:/data/db

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always

  discountdb:
    image: postgres:16-alpine
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@1
      - POSTGRES_DB=DiscountDbdockere 
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  orderingdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderingdb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1
    volumes:
      - mssql_data:/var/opt/mssql

  catalog.api:
    image: catalogapi
    container_name: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    restart: always
    depends_on:
      - catalogdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://catalogdb:27017
      - MongoDbSettings__DatabaseName=CatalogDb

  basket.api:
    image: basketapi
    container_name: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    restart: always
    depends_on:
      - basketdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=basketdb:6379

  discount.api:
    image: discountapi
    container_name: discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    restart: always
    depends_on:
      - discountdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;

  ordering.api:
    image: orderingapi
    container_name: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    restart: always
    depends_on:
      - orderingdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mongo_data:
  postgres_data:
  mssql_data: